### ISSUE TITLE
Please remove bundled maude-mode.el

### ISSUE THREAD

**Issue by tarsius** [abstools/abs-mode#2]
Bundling third-party libraries is never a good idea. It makes live harder for people who install packages by running them directly from their git repositories. If someone has installed both the `abs-mode` and the `maude-mode` packages, then it is undefined which one gets loaded. It would be unfortunate if the outdated bundled version were loaded.

Thanks!

**Comment by rudi** [comment]
Completely agreed - this is a leftover from the monorepo that abs-mode started in.  That said, if my understanding is correct, the file maude-mode.el shouldn't be installed when a user installs abs-mode?  Nevertheless, I'll remove it.

**Comment by rudi** [comment]
Nevermind - you answered my idle question in your report already.  Thanks again for reporting!

**Comment by tarsius** [comment]
Thanks!
